set(INSTALL_DIRS
	${SRC_ROOT}/StepNN/Neural/Data
	${SRC_ROOT}/StepNN/Neural/Interfaces
	${SRC_ROOT}/StepNN/Neural/Layer/Settings
)

# Install
set(INSTALLED_TARGETS StepNN)
install(
	TARGETS ${INSTALLED_TARGETS}
	LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/${PROJECT_NAME}/lib
	ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/${PROJECT_NAME}/lib
	RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/${PROJECT_NAME}/bin
)

foreach(exportDir ${INSTALL_DIRS})
	install(
		DIRECTORY ${exportDir}
		DESTINATION ${CMAKE_INSTALL_PREFIX}/${PROJECT_NAME}/include/StepNN
		FILES_MATCHING PATTERN "*.h*"
	)
endforeach()


